services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    restart: always
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    env_file:
    - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
  postgres:
    build:
      dockerfile: ./db/Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  docker-nest-postgres: